IMAGE_NAME=$1
IMAGE_TAG=$2
DOCKER_REGISTRY_URL=$3
DOCKER_REGISTRY_PASSWORD=$4
docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL
docker build -t $DOCKER_REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG -t $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest .
docker push $DOCKER_REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest