IMAGE_NAME=
IMAGE_TAG=
DOCKER_REGISTRY_URL=
DOCKER_REGISTRY_PASSWORD=
docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL
docker build -t $DOCKER_REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG -t $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest .
docker push $DOCKER_REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest