printEnvGitlab(){
  echo   "gitlabBranch: $gitlabBranch"
  echo   "gitlabSourceBranch: $gitlabSourceBranch"
  echo   "gitlabActionType: $gitlabActionType"
  echo   "gitlabUserName: $gitlabUserName"
  echo   "gitlabUserUsername: $gitlabUserUsername"
  echo   "gitlabUserEmail: $gitlabUserEmail"
  echo   "gitlabSourceRepoHomepage: $gitlabSourceRepoHomepage"
  echo   "gitlabSourceRepoName: $gitlabSourceRepoName"
  echo   "gitlabSourceNamespace: $gitlabSourceNamespace"
  echo   "gitlabSourceRepoURL: $gitlabSourceRepoURL"
  echo   "gitlabSourceRepoSshUrl: $gitlabSourceRepoSshUrl"
  echo   "gitlabSourceRepoHttpUrl: $gitlabSourceRepoHttpUrl"
  echo   "gitlabMergeRequestTitle: $gitlabMergeRequestTitle"
  echo   "gitlabMergeRequestDescription: $gitlabMergeRequestDescription"
  echo   "gitlabMergeRequestId: $gitlabMergeRequestId"
  echo   "gitlabMergeRequestIid: $gitlabMergeRequestIid"
  echo   "gitlabMergeRequestState: $gitlabMergeRequestState"
  echo   "gitlabMergedByUser: $gitlabMergedByUser"
  echo   "gitlabMergeRequestAssignee: $gitlabMergeRequestAssignee"
  echo   "gitlabMergeRequestLastCommit: $gitlabMergeRequestLastCommit"
  echo   "gitlabMergeRequestTargetProjectId: $gitlabMergeRequestTargetProjectId"
  echo   "gitlabTargetBranch: $gitlabTargetBranch"
  echo   "gitlabTargetRepoName: $gitlabTargetRepoName"
  echo   "gitlabTargetNamespace: $gitlabTargetNamespace"
  echo   "gitlabTargetRepoSshUrl: $gitlabTargetRepoSshUrl"
  echo   "gitlabTargetRepoHttpUrl: $gitlabTargetRepoHttpUrl"
  echo   "gitlabBefore: $gitlabBefore"
  echo   "gitlabAfter: $gitlabAfter"
  echo   "gitlabTriggerPhrase: $gitlabTriggerPhrase"
}


printEnvGitlab